"""initial schema

Revision ID: 0504db5a33ca
Revises: 
Create Date: 2026-05-17 01:57:28.802114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0504db5a33ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('goal_setting_opens', sa.Date(), nullable=False),
    sa.Column('q1_opens', sa.Date(), nullable=False),
    sa.Column('q2_opens', sa.Date(), nullable=False),
    sa.Column('q3_opens', sa.Date(), nullable=False),
    sa.Column('q4_opens', sa.Date(), nullable=False),
    sa.Column('current_phase', sa.Enum('closed', 'goal_setting', 'q1', 'q2', 'q3', 'q4_annual', name='cyclephase', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('thrust_areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'manager', 'admin', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('thrust_area_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('uom_type', sa.Enum('numeric_min', 'numeric_max', 'percent_min', 'percent_max', 'timeline', 'zero', name='uomtype', native_enum=False, length=20), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('weightage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'locked', name='goalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('shared_parent_id', sa.Uuid(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_parent_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['thrust_area_id'], ['thrust_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_cycle_id'), 'goals', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_goals_employee_id'), 'goals', ['employee_id'], unique=False)
    op.create_table('achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('quarter', sa.Enum('q1', 'q2', 'q3', 'q4', name='quarter', native_enum=False, length=20), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'on_track', 'completed', name='achievementstatus', native_enum=False, length=20), nullable=False),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'quarter', name='uq_achievement_goal_quarter')
    )
    op.create_index(op.f('ix_achievements_goal_id'), 'achievements', ['goal_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('field_changed', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_goal_id_timestamp', 'audit_log', ['goal_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_goal_id_timestamp', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_achievements_goal_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_goals_employee_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_cycle_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('thrust_areas')
    op.drop_table('cycles')
    # ### end Alembic commands ###
